//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assignment1.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login App.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Explanation.
        /// </summary>
        public static string HideExplanationLabel {
            get {
                return ResourceManager.GetString("HideExplanationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User name or Password. Please try again..
        /// </summary>
        public static string LoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome User: .
        /// </summary>
        public static string LoginSuccessfulMessage {
            get {
                return ResourceManager.GetString("LoginSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option if you use Outlook Web App
        ///on a public computer.  Be sure to sign out when 
        ///you&apos;ve finished and close all windows to end
        ///your session..
        /// </summary>
        public static string PrivateComputerExplanationTxt {
            get {
                return ResourceManager.GetString("PrivateComputerExplanationTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a private computer.
        /// </summary>
        public static string PrivateComputerRadioButton {
            get {
                return ResourceManager.GetString("PrivateComputerRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option if you&apos;re the only person who 
        ///uses this computer. Your server will allow a longer 
        ///period of inactivity before signing you out..
        /// </summary>
        public static string PublicComputerExplanationTxt {
            get {
                return ResourceManager.GetString("PublicComputerExplanationTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a public or shared computer.
        /// </summary>
        public static string PublicComputerRadioButton {
            get {
                return ResourceManager.GetString("PublicComputerRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string SecurityLabel {
            get {
                return ResourceManager.GetString("SecurityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Explanation.
        /// </summary>
        public static string ShowExplanationLabel {
            get {
                return ResourceManager.GetString("ShowExplanationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignInLabel {
            get {
                return ResourceManager.GetString("SignInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the light version of 
        ///Outlook Web App.
        /// </summary>
        public static string UseLightVersionCheckBox {
            get {
                return ResourceManager.GetString("UseLightVersionCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Here.
        /// </summary>
        public static string UseLightVersionMoreInfoBtn {
            get {
                return ResourceManager.GetString("UseLightVersionMoreInfoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://help.outlook.com/en-us/140/bb899685.aspx.
        /// </summary>
        public static string UseLightVersionMoreInfoLink {
            get {
                return ResourceManager.GetString("UseLightVersionMoreInfoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The light version of Outlook Web App 
        ///includes fewer features. Use it if you&apos;re 
        ///on a slow connection or using a computer 
        ///with unusually strict browser security settings.
        /// We also support the full Outlook Web App 
        ///experience on some browsers on 
        ///Windows, Mac, and Linux computers. To check 
        ///out all the supported browsers and 
        ///operating systems:.
        /// </summary>
        public static string UseLightVersionTxt {
            get {
                return ResourceManager.GetString("UseLightVersionTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        public static string UserNameLabel {
            get {
                return ResourceManager.GetString("UserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: By selecting this option,
        ///you confirm that this computer complies
        ///with your organization&apos;s security policy..
        /// </summary>
        public static string WarningPrivateComputerTxt {
            get {
                return ResourceManager.GetString("WarningPrivateComputerTxt", resourceCulture);
            }
        }
    }
}
